name: release-pr
on:
  workflow_dispatch:
    inputs:
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v2.19.2
        with:
          release-type: simple
          command: release-pr
