name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        id: release
        uses: google-github-actions/release-please-action@v2.19.2
        with:
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - run: |
          echo ${{ steps.release.outputs.release_created }}
      - if: ${{ steps.release.outputs.release_created }}
        run: |
          echo release created1
      - if: ${{ steps.release.outputs.release_created }} == 'true'
        run: |
          echo release created2
      - if: ${{ steps.release.outputs.release_created == 'true'}}
        run: |
          echo release created4
      - if: ${{ steps.release.outputs.release_created == false}}
        run: |
          echo release is not created3
      - if: ${{ steps.release.outputs.release_created == 'false'}}
        run: |
          echo release is not created4
  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: always()
    steps:
      - run: |
          echo ${{needs.release-please.steps.release.outputs.release_created}}
      - if: ${{ needs.release-please.steps.release.outputs.release_created }}
        run: |
          echo release created1
      - if: ${{ needs.release-please.steps.release.outputs.release_created }} == 'true'
        run: |
          echo release created2
      - if: ${{ needs.release-please.steps.release.outputs.release_created == true}}
        run: |
          echo release created3
      - if: ${{ needs.release-please.steps.release.outputs.release_created == 'true'}}
        run: |
          echo release created4
      - if: ${{ needs.release-please.steps.release.outputs.release_created }} == 'false'
        run: |
          echo release is not created2
      - if: ${{ needs.release-please.steps.release.outputs.release_created == false}}
        run: |
          echo release is not created3
      - if: ${{ needs.release-please.steps.release.outputs.release_created == 'false'}}
        run: |
          echo release is not created4
